### ISSUE TITLE
No comments in the code

### ISSUE THREAD

**Issue by Tom-ne** [Ilanox/Gloasty#14]
It's really hard to understand what each part of the code does because there aren't any comments or docs

**Comment by Ilanox** [comment]
I'm working on a Wiki right now actually :)

**Comment by Tom-ne** [comment]
lol

‫בתאריך יום א׳, 14 באוג׳ 2022 ב-23:57 מאת ‪Ilanox‬‏ <‪
***@***.***‬‏>:‬

**Comment by Tom-ne** [comment]
lol
